In [1]:
import pandas as pd

In [25]:
base_path = '../../data/insumos 19 junio/'
source_name = '20260615_Costeo_Adición_HCB_Julio_Octubre_costeo_actualizadoV5 1.xlsx'

In [26]:
contratos = pd.read_excel(base_path + source_name, sheet_name='COSTEO', dtype={'No. Contrato': str})

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [18]:
contratos.head(2)

,ZONA 2026.,No. Contrato,Entidad Contratista 2026,Numero DocumentoEC,Regional UDS,Municipio UDS,Centro Zonal UDS,CodigoUnidadServicioUDS,Unidad Servicio UDS,SERVICIO 2026,...,TIPO DE CONTRATACIÓN 2026,OBSERVACIONES,TIPO,DESDE,HASTA,SUBTOTAL,Trabajadoras Oficiales,Valor Ref Trabajadora Oficial,Valor Total Trab. Ofi. \n(Vlr Madre* Cant TO * 4 meses),TOTAL\n(Sub total - Vlr TO)
0,122,11026112024,ASOCIACION DE PADRES USUARIOS DE LOS HOGARES D...,800211026,Bogota D.C.,"Bogota, D.C.",CZ KENNEDY,1100100135350,MI PEQUEÑO HOGAR,HCB - FAMILIAR Y COMUNITARIA,...,Articulo 35 invitación cerrada – literal m,NaN,HCB,JULIO,OCTUBRE,20633062,0.0,0,0,20633062
1,122,11026112024,ASOCIACION DE PADRES USUARIOS DE LOS HOGARES D...,800211026,Bogota D.C.,"Bogota, D.C.",CZ KENNEDY,1100100135384,ALDEA PITUFA 2,HCB - FAMILIAR Y COMUNITARIA,...,Articulo 35 invitación cerrada – literal m,NaN,HCB,JULIO,OCTUBRE,20633062,0.0,0,0,20633062

In [19]:
contratos['Regional UDS'] = contratos['Regional UDS'].str.title()
len(contratos['Regional UDS'].value_counts())

29

In [20]:
sorted(contratos.columns)

['Centro Zonal UDS',
 'CodigoUnidadServicioUDS',
 'Componente para la UDS',
 'Cupos ABRIL 2026',
 'Cupos a \nProgramar 2026',
 'DESDE',
 'ESTADO DE UDS',
 'Entidad Contratista 2026',
 'HASTA',
 'Municipio UDS',
 'No. Contrato',
 'Numero DocumentoEC',
 'Numero de Madres Comunitarias por UDS / numero de unidades',
 'OBSERVACIONES',
 'Regional UDS',
 'SERVICIO 2026',
 'SUBTOTAL',
 'TIPO',
 'TIPO DE CONTRATACIÓN 2026',
 'TOTAL\n(Sub total - Vlr TO)',
 'Trabajadoras Oficiales',
 'UDS a programar en 2026 (SI/NO)',
 'Unidad Servicio UDS',
 'Valor Ref Trabajadora Oficial',
 'Valor Total Trab. Ofi. \n(Vlr Madre* Cant TO * 4 meses)',
 'ZONA 2026.']

In [23]:
target_columns = ['Regional UDS', 'No. Contrato']
contratos_res = contratos[target_columns].drop_duplicates().reset_index(drop=True)

print('contratos: ', len(contratos))
print('contratos_res: ', len(contratos_res))

contratos:  33248
contratos_res:  1450

In [24]:
contratos_res['PACCO'] = ''
contratos_res['CDP'] = ''
contratos_res['SITCO'] = ''
contratos_res['Estudios Previos'] = ''
contratos_res['Documentos del Operador'] = ''
contratos_res['Radicación Jurídica'] = ''
contratos_res['SECOP'] = ''
contratos_res['Póliza'] = ''
contratos_res['RP'] = ''
contratos_res['Referencia de Contrato'] = ''
contratos_res['Categoria EAS'] = ''

contratos_res.head(2)

,Regional UDS,No. Contrato,PACCO,CDP,SITCO,Estudios Previos,Documentos del Operador,Radicación Jurídica,SECOP,Póliza,RP,Referencia de Contrato,Categoria EAS
0,Bogota D.C.,11026112024,,,,,,,,,,,
1,Bogota D.C.,11026122024,,,,,,,,,,,

In [31]:
for regional in contratos_res['Regional UDS'].unique():
    contratos_res[contratos_res['Regional UDS'] == regional].to_excel(base_path + 'Ranking/' + f'ranking_{regional}.xlsx', index=False)

In [27]:
contratos_res.to_excel(base_path + 'ranking.xlsx', index=False)