In [1]:
import pandas as pd

In [2]:
base_path = '../../data/insumos 19 junio/'
original_source_name = '20260615_Costeo_Adición_HCB_Julio_Octubre_costeo_actualizadoV5 1.xlsx'
new_source_name = '20260619_Costeo_Adición_HCB_Julio_Octubre_costeo_actualizadoV10 1.xlsx'

In [4]:
original_source = pd.read_excel(base_path + original_source_name, sheet_name='COSTEO', dtype={'No. Contrato': str})
print(len(original_source))
original_source.head(2)

33248

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,ZONA 2026.,No. Contrato,Entidad Contratista 2026,Numero DocumentoEC,Regional UDS,Municipio UDS,Centro Zonal UDS,CodigoUnidadServicioUDS,Unidad Servicio UDS,SERVICIO 2026,...,TIPO DE CONTRATACIÓN 2026,OBSERVACIONES,TIPO,DESDE,HASTA,SUBTOTAL,Trabajadoras Oficiales,Valor Ref Trabajadora Oficial,Valor Total Trab. Ofi. \n(Vlr Madre* Cant TO * 4 meses),TOTAL\n(Sub total - Vlr TO)
0,122,11026112024,ASOCIACION DE PADRES USUARIOS DE LOS HOGARES D...,800211026,Bogota D.C.,"Bogota, D.C.",CZ KENNEDY,1100100135350,MI PEQUEÑO HOGAR,HCB - FAMILIAR Y COMUNITARIA,...,Articulo 35 invitación cerrada – literal m,NaN,HCB,JULIO,OCTUBRE,20633062,0.0,0,0,20633062
1,122,11026112024,ASOCIACION DE PADRES USUARIOS DE LOS HOGARES D...,800211026,Bogota D.C.,"Bogota, D.C.",CZ KENNEDY,1100100135384,ALDEA PITUFA 2,HCB - FAMILIAR Y COMUNITARIA,...,Articulo 35 invitación cerrada – literal m,NaN,HCB,JULIO,OCTUBRE,20633062,0.0,0,0,20633062

In [5]:
new_source = pd.read_excel(base_path + new_source_name, sheet_name='COSTEO', dtype={'No. Contrato': str})
print(len(new_source))
new_source.head(2)

33248

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,ZONA 2026.,No. Contrato,Entidad Contratista 2026,Numero DocumentoEC,Regional UDS,Municipio UDS,Centro Zonal UDS,CodigoUnidadServicioUDS,Unidad Servicio UDS,SERVICIO 2026,...,TIPO DE CONTRATACIÓN 2026,OBSERVACIONES,TIPO,DESDE,HASTA,SUBTOTAL,Trabajadoras Oficiales,Valor Ref Trabajadora Oficial,Valor Total Trab. Ofi. \n(Vlr Madre* Cant TO * 4 meses),TOTAL\n(Sub total - Vlr TO)
0,122,11026112024,ASOCIACION DE PADRES USUARIOS DE LOS HOGARES D...,800211026,Bogota D.C.,"Bogota, D.C.",CZ KENNEDY,1100100135350,MI PEQUEÑO HOGAR,HCB - FAMILIAR Y COMUNITARIA,...,Articulo 35 invitación cerrada – literal m,NaN,HCB,JULIO,OCTUBRE,20633062,0,0,0,20633062
1,122,11026112024,ASOCIACION DE PADRES USUARIOS DE LOS HOGARES D...,800211026,Bogota D.C.,"Bogota, D.C.",CZ KENNEDY,1100100135384,ALDEA PITUFA 2,HCB - FAMILIAR Y COMUNITARIA,...,Articulo 35 invitación cerrada – literal m,NaN,HCB,JULIO,OCTUBRE,20633062,0,0,0,20633062

In [9]:
original_source['Regional UDS'] = original_source['Regional UDS'].str.title()
new_source['Regional UDS'] = new_source['Regional UDS'].str.title()

original_source_contracts_by_regional = original_source[['No. Contrato', 'Regional UDS']].drop_duplicates()
new_source_contracts_by_regional = new_source[['No. Contrato', 'Regional UDS']].drop_duplicates()

print(len(original_source_contracts_by_regional))
print(len(new_source_contracts_by_regional))

1450
1437

In [10]:
original_new_contracts = pd.merge(
    left=original_source_contracts_by_regional, right=new_source_contracts_by_regional,
    how='outer', on=['No. Contrato', 'Regional UDS'], indicator=True)

original_new_contracts['_merge'].value_counts()

_merge
both          1436
left_only       14
right_only       1
Name: count, dtype: int64

In [20]:
original_new_contracts[original_new_contracts['_merge'] == 'left_only'].reset_index()[['No. Contrato', 'Regional UDS']]

   No. Contrato Regional UDS
0   23007862024      Córdoba
1   23008132024      Córdoba
2   23008292024      Córdoba
3   23008422024      Córdoba
4   23008452024      Córdoba
5   23008472024      Córdoba
6   23008532024      Córdoba
7   47006992024    Magdalena
8   47007012024    Magdalena
9   47007212024    Magdalena
10  47007502024    Magdalena
11  47007862024    Magdalena
12  52009852024       Nariño
13  52010592024       Nariño

In [21]:
original_new_contracts[original_new_contracts['_merge'] == 'right_only'].reset_index()[['No. Contrato', 'Regional UDS']]

  No. Contrato Regional UDS
0   8600410202     Putumayo