In [37]:
import pandas as pd

In [38]:
base_path = "D:/ICBF/cost-tracking/data/insumos 4 junio/"

abastecimiento = 'zonificación_abastecimiento_servicios_primera_infancia25052026.xlsx'
cuentame = 'ICBFCUEUnidadesServicio (8).xlsx'
cuentame_2025 = 'UDS_15052026_3112025.xlsx'
formato = 'zonificación_integrales_2026_ajustado.xlsx'

In [39]:
abastecimiento_df = pd.read_excel(base_path + abastecimiento, sheet_name='Integrales-Convenios', dtype={'Codigo Unidad Servicio UDS': str})
abastecimiento_df.head(2)

,Zona,Regional UDS,Centro Zonal UDS,Municipio UDS,Codigo Unidad Servicio UDS,Unidad Servicio UDS,LITERAL DE CONTRATACION,LITERAL DE CONTRATACION ALTERNATIVO,SERVICIO 2026,Componente para la UDS,Desde,Hasta,Cupos,Alistamiento,Canasta Mes,Variables,Alimentación,Dotación,Costo total
0,1,Amazonas,CZ LETICIA,Leticia,910011125968,BELLO RENACER,Articulo 35 invitación cerrada – literal m,Articulo 35 Invitación Cerrada – literal h,CENTRO DE DESARROLLO INFANTIL - D – INSTITUCIONAL,OPERADOR COMPONENTE PEDAGOGICO CON ALIMENTOS,Agosto,Octubre,126,0,160214544.0,4520577.6,55069194.6,0,219804316.2
1,1,Amazonas,CZ LETICIA,Leticia,9100100037607,BUATACHICA,Articulo 35 invitación cerrada – literal m,Articulo 35 Invitación Cerrada – literal h,CENTRO DE DESARROLLO INFANTIL - D – INSTITUCIONAL,OPERADOR COMPONENTE PEDAGOGICO CON ALIMENTOS,Agosto,Octubre,104,0,132240576.0,3731270.4,45453938.4,0,181425784.8

In [40]:
cuentame_df = pd.read_excel(base_path + cuentame, sheet_name='ICBFCUEUnidadesServicio', dtype={'Código UDS': str})
cuentame_df.head(2)

,Tipo de Unidad,Nombre Entidad Contratista,Tipo Documento EC,Identificación EC,Nombre Tipo Organización EC,Departamento EC,Municipio EC,Regional Contrato,No. Contrato,Regional UDS,...,Hogar Funciona En Su Vivienda,Servicios Publicos,Estrato Lugar Funciona Hogar,Tipo Vivienda Ocupada Por Familia,Fecha de Vinculación,Fecha Desvinculación,Estado de la UDS,Estado UDS Contrato,Número de cupos del servicio,Número de beneficiarios activos UDS
0,Unidad de Servicio,ASOCIACION DE PADRES DE FAMILIA DE HOGARES COM...,NUMERO DE IDENTIFICACION TRIBUTARIA,806004938.0,ASOCIACIONES DE PADRES DE FAMILIA,BOLÍVAR,CARTAGENA DE INDIAS,BOLÍVAR,13010642024,BOLÍVAR,...,SI,SI,1.0,PROPIA,09/03/2026,NaN,ACTIVA,Activo,299.0,13.0
1,Unidad de Servicio,INSTITUTO COLOMBIANO DE BIENESTAR FAMILIAR ICBF,NUMERO DE IDENTIFICACION TRIBUTARIA,899999239.0,ENTIDAD PÚBLICA DEL ORDEN NACIONAL,BOGOTA D.C.,"BOGOTA, D.C.",VAUPÉS,OD 97 420259 00606 2026,VAUPÉS,...,NaN,SI,NaN,NaN,10/04/2026,NaN,ACTIVA,Activo,137.0,41.0

In [41]:
cuentame_2025_df = pd.read_excel(base_path + cuentame_2025, sheet_name='UDS_31122025', dtype={'CodigoUnidadServicioUDS': str})
cuentame_2025_df.head(2)

,TipoUnidad,EntidadContratista,TipoDocumentoEC,NumeroDocumentoEC,TipoOrganizacionEC,CodigoDepartamentoEC,DepartamentoEC,CodigoMunicipioEC,MunicipioEC,RegionalContrato,...,FechaCapturaUDS,HoraCapturaUDS,ServicioAlcantarillado,ServicioLuz,ServicioGas,ServicioTelefoniaFija,ServicioInternet,ServicioRecoleccionBasuras,ServicioAgua,ServicioTelefoniaMovil
0,SEDE EDUCATIVA,ASOCIACION COMPAZ,NUMERO DE IDENTIFICACION TRIBUTARIA,825002581.0,ASOCIACIONES,44.0,LA GUAJIRA,44279.0,FONSECA,LA GUAJIRA,...,2024-06-11 00:00:00.000,11:11:11,N,N,N,N,N,N,N,N
1,SEDE EDUCATIVA,ASOCIACION COMPAZ,NUMERO DE IDENTIFICACION TRIBUTARIA,825002581.0,ASOCIACIONES,44.0,LA GUAJIRA,44279.0,FONSECA,LA GUAJIRA,...,2024-06-11 00:00:00.000,11:11:11,N,N,N,N,N,N,N,N

In [42]:
formato_df = pd.read_excel(base_path + formato, sheet_name='zonificacion')
formato_df.head(2)

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Número de Zona,Número de contrato,Identificación EC,Entidad Contratista\n2026,Modalidad\n2026,Servicio 2026,Regional UDS,Departamento UDS,Municipio UDS,Divipola,...,UDS en territorio étnico \n(SI /NO),Cantidad Madres \nLaboralizadas en la UDS,Cantidad Madres\n Tránsito en la UDS,"Observaciones \n(Alertas de infraestructuras, de coberturas, etc)",Observaciones Dotacion,¿Cuenta con la Valoración de la familia?,Concepto de continuidad de la EAS por el supervisor,Concepto de continuidad,Literal de contratación,Procedimiento para contratar
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
sorted(abastecimiento_df.columns)

['Alimentación',
 'Alistamiento',
 'Canasta Mes',
 'Centro Zonal UDS',
 'Codigo Unidad Servicio UDS',
 'Componente para la UDS',
 'Costo total ',
 'Cupos',
 'Desde',
 'Dotación',
 'Hasta',
 'LITERAL DE CONTRATACION',
 'LITERAL DE CONTRATACION ALTERNATIVO',
 'Municipio UDS',
 'Regional UDS',
 'SERVICIO 2026',
 'Unidad Servicio UDS',
 'Variables',
 'Zona ']

In [44]:
sorted(cuentame_df.columns)

['Año Biblioteca Infantil UDS',
 'Barrio UDS',
 'Cantidad Cojines UDS',
 'Cantidad Estantes UDS',
 'Cantidad Libros UDS',
 'Centro Poblado UDS',
 'Centro Zonal UDS',
 'Codigo Captura UDS',
 'Comuna UDS',
 'Cupos UDS',
 'Código UDS',
 'Departamento EC',
 'Departamento UDS',
 'Dirección UDS',
 'Estado UDS Contrato',
 'Estado de la UDS',
 'Estrato Lugar Funciona Hogar',
 'Fecha Captura UDS',
 'Fecha Desvinculación',
 'Fecha de Vinculación',
 'Hogar Funciona En Su Vivienda',
 'Hora Captura UDS',
 'Identificación EC',
 'Identificación Responsable UDS',
 'Infraestructura UDS Propiedad Icbf ',
 'La Unidad De Servicio Es',
 'Latitud UDS',
 'Longitud UDS',
 'Municipio EC',
 'Municipio UDS',
 'No. Contrato',
 'Nombre Entidad Contratista',
 'Nombre Servicio',
 'Nombre Tipo Organización EC',
 'Número de beneficiarios activos UDS',
 'Número de cupos del servicio',
 'Primer Apellido',
 'Primer Nombre',
 'Regional Contrato',
 'Regional UDS',
 'Segundo Apellido',
 'Segundo Nombre',
 'Servicios Publicos',
 'Teléfono UDS',
 'Tiene Biblioteca Infantil UDS',
 'Tipo Documento EC',
 'Tipo Vivienda Ocupada Por Familia',
 'Tipo de Unidad',
 'Unidad De Servicio (UDS)',
 'Vigencia',
 'Zona Resto UDS',
 'Zona Ubicación UDS']

In [45]:
sorted(formato_df.columns)

['Barrio UDS',
 'CAMBIO SERVICIO ',
 'Cantidad Madres\n Tránsito en la UDS',
 'Cantidad Madres \nLaboralizadas en la UDS',
 'Centro Zonal UDS',
 'Cod CZ',
 'Codigo Unidad Servicio UDS',
 'Concepto de No programación',
 'Concepto de continuidad ',
 'Concepto de continuidad de la EAS por el supervisor',
 'Cupos UDS ofertados 2026',
 'Cupos a Programar 2026\nII Semestre',
 'Departamento UDS',
 'Direccion UDS',
 'Divipola',
 'Entidad Contratista\n2026',
 'Estado UDS',
 'Identificación EC',
 'Literal de contratación ',
 'Modalidad\n2026',
 'Modalidad 2026\nII Semestre',
 'Municipio UDS',
 'Número de Zona',
 'Número de contrato ',
 'Observaciones \n(Alertas de infraestructuras, de coberturas, etc)',
 'Observaciones Dotacion',
 'Procedimiento para contratar',
 'Propiedad de \nla infraestructura ',
 'Regional UDS',
 'SERVICIO \n2026\nII Semestre',
 'Servicio 2026',
 'UDS a programar en 2026 (SI/NO)',
 'UDS en territorio étnico \n(SI /NO)',
 'Unidad Servicio UDS',
 'Vigencia UDS',
 '¿Cuenta con la Valoración de la familia?']

In [46]:
formato_df['¿Cuenta con la Valoración de la familia?'].value_counts()

Series([], Name: count, dtype: int64)

In [47]:
abastecimiento_df['Zona '].value_counts()

Zona
24        144
1632      123
1234C     103
1511       94
1191-O     93
         ...
452-B       1
452-C       1
452-D       1
521-A       1
671-C       1
Name: count, Length: 1836, dtype: int64

In [48]:
cuentame_df['Vigencia'].value_counts()

Vigencia
2026    63279
Name: count, dtype: int64

In [49]:
cuentame_columns = ['Barrio UDS', 'Departamento UDS', 'Direccion UDS', 'Nombre Entidad Contratista', 'Estado de la UDS', 'No. Contrato', 
                    'Nombre Servicio', 'Vigencia', 'Código UDS', 'Identificación EC',
                    'Regional UDS', 'Municipio UDS', 'Centro Zonal UDS']
cuentame_2025_columns = ['BarrioUDS', 'DepartamentoUDS', 'DireccionUDS', 'EntidadContratista', 'EstadoUDS', 'NumeroContrato', 'Servicio', 
                         'VigenciaServicio', 'CodigoUnidadServicioUDS', 'NumeroDocumentoEC',
                         'RegionalUDS', 'MunicipioUDS', 'CentroZonalUDS']
abastecimiento_columns = ['Centro Zonal UDS', 'Codigo Unidad Servicio UDS', 'Municipio UDS', 'Regional UDS', 'Unidad Servicio UDS', 
                         'Cupos', 'Zona ', 'SERVICIO 2026']
empty_columns = ['CAMBIO SERVICIO ', 'Cantidad Madres\n Tránsito en la UDS', 'Cantidad Madres \nLaboralizadas en la UDS', 'Cod CZ',
                 'Concepto de No programación', 'Concepto de continuidad ', 'Concepto de continuidad de la EAS por el supervisor',
                 'Cupos a Programar 2026\nII Semestre', 'Divipola', 'Literal de contratación ', 'Modalidad 2026\nII Semestre',
                 'Observaciones \n(Alertas de infraestructuras, de coberturas, etc)', 'Observaciones Dotacion', 'Procedimiento para contratar',
                 'Propiedad de \nla infraestructura ', 'SERVICIO \n2026\nII Semestre', 'UDS a programar en 2026 (SI/NO)',
                 'UDS en territorio étnico \n(SI /NO)', '¿Cuenta con la Valoración de la familia?']

mapped_columns = {'Modalidad\n2026': 'INTEGRAL'}

rename_dict = {
    'Cupos': 'Cupos UDS ofertados 2026',
    'Nombre Entidad Contratista': 'Entidad Contratista\n2026',
    'Estado de la UDS': 'Estado UDS',
    'Identificación EC': 'NIT_EntidadContratista',
    'Zona ': 'Número de Zona',
    'No. Contrato': 'Número de contrato ',
    'SERVICIO 2026': 'Servicio 2026',
    'Vigencia': 'Vigencia UDS',
    'Departamento UDS': 'Departamento UDS',
    'Barrio UDS': 'Barrio UDS',
    'Dirección UDS': 'Direccion UDS',
    'Cupos': 'Cupos UDS ofertados 2026',
    'BarrioUDS': 'Barrio UDS',
    'DepartamentoUDS': 'Departamento UDS',
    'DireccionUDS': 'Direccion UDS',
    'EntidadContratista': 'Entidad Contratista\n2026',
    'EstadoUDS': 'Estado UDS',
    'NumeroContrato': 'Número de contrato ',
    'VigenciaServicio': 'Vigencia UDS',
    'CodigoUnidadServicioUDS': 'Código UDS',
    'NumeroDocumentoEC': 'NIT_EntidadContratista'
}

In [50]:
abastecimient_df_exclude_columns = abastecimiento_df.loc[:, abastecimiento_df.columns.isin(abastecimiento_columns)]
abastecimient_df_exclude_columns.head(2)

,Zona,Regional UDS,Centro Zonal UDS,Municipio UDS,Codigo Unidad Servicio UDS,Unidad Servicio UDS,SERVICIO 2026,Cupos
0,1,Amazonas,CZ LETICIA,Leticia,910011125968,BELLO RENACER,CENTRO DE DESARROLLO INFANTIL - D – INSTITUCIONAL,126
1,1,Amazonas,CZ LETICIA,Leticia,9100100037607,BUATACHICA,CENTRO DE DESARROLLO INFANTIL - D – INSTITUCIONAL,104

In [51]:
cuentame_df_exclude_columns = cuentame_df.loc[:, cuentame_df.columns.isin(cuentame_columns)]
cuentame_df_exclude_columns.head(2)

,Nombre Entidad Contratista,Identificación EC,No. Contrato,Regional UDS,Código UDS,Centro Zonal UDS,Departamento UDS,Municipio UDS,Barrio UDS,Nombre Servicio,Vigencia,Estado de la UDS
0,ASOCIACION DE PADRES DE FAMILIA DE HOGARES COM...,806004938.0,13010642024,BOLÍVAR,130011124790,CZ INDUSTRIAL DE LA BAHIA,BOLÍVAR,CARTAGENA DE INDIAS,SAN JOSE DE LOS CAMPANOS,HCB - FAMILIAR Y COMUNITARIA,2026,ACTIVA
1,INSTITUTO COLOMBIANO DE BIENESTAR FAMILIAR ICBF,899999239.0,OD 97 420259 00606 2026,VAUPÉS,970011162912,CZ MITU,VAUPÉS,MITU,NaN,CENTRO DE DESARROLLO INFANTIL - SIN ARRIENDO -...,2026,ACTIVA

In [52]:
# --- NORMALIZAR TODO A MAYUSCULAS ---
for df in [abastecimient_df_exclude_columns, cuentame_df_exclude_columns, cuentame_2025_df]:
    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip().str.upper()

# --- LLAVE COMPUESTA 1er MERGE (UDS + SERVICIO + UBICACION) ---
left_keys = ['Codigo Unidad Servicio UDS', 'SERVICIO 2026', 'Regional UDS', 'Municipio UDS', 'Centro Zonal UDS']
right_keys = ['Código UDS', 'Nombre Servicio', 'Regional UDS', 'Municipio UDS', 'Centro Zonal UDS']

cuentame_dedup = cuentame_df_exclude_columns.drop_duplicates(subset=right_keys, keep='first')

abastecimiento_cuentame = abastecimient_df_exclude_columns.merge(
    cuentame_dedup,
    left_on=left_keys,
    right_on=right_keys,
    how='left',
    suffixes=('', '_cuentame'),
    indicator=True)

for c in [c for c in abastecimiento_cuentame.columns if c.endswith('_cuentame')]:
    abastecimiento_cuentame.drop(columns=[c], inplace=True)

abastecimiento_no_cruza_comp = abastecimiento_cuentame[abastecimiento_cuentame['_merge'] == 'left_only'][abastecimiento_columns].copy()
abastecimiento_cuentame = abastecimiento_cuentame[abastecimiento_cuentame['_merge'] != 'left_only']
abastecimiento_cuentame.drop(columns=['_merge'], inplace=True)

# --- FALLBACK: las no match, solo por UDS contra cuentame ---
cuentame_uds = cuentame_df_exclude_columns.drop_duplicates(subset='Código UDS', keep='first')
fb = abastecimiento_no_cruza_comp.merge(
    cuentame_uds,
    left_on='Codigo Unidad Servicio UDS',
    right_on='Código UDS',
    how='left',
    suffixes=('', '_cuentame'),
    indicator=True)

for c in [c for c in fb.columns if c.endswith('_cuentame')]:
    fb.drop(columns=[c], inplace=True)

abastecimiento_no_cruza_uds = fb[fb['_merge'] == 'left_only'][abastecimiento_columns].copy()
fb = fb[fb['_merge'] != 'left_only']
fb.drop(columns=['_merge'], inplace=True)
abastecimiento_cuentame = pd.concat([abastecimiento_cuentame, fb])
abastecimiento_cuentame.rename(columns=rename_dict, inplace=True)

# --- ULTIMO FALLBACK: cuentame_2025 solo por UDS ---
cue2025_uds = cuentame_2025_df[cuentame_2025_columns].drop_duplicates(subset='CodigoUnidadServicioUDS', keep='first')
abastecimiento_cuentame_2025 = abastecimiento_no_cruza_uds.merge(
    cue2025_uds,
    left_on='Codigo Unidad Servicio UDS',
    right_on='CodigoUnidadServicioUDS',
    how='left',
    suffixes=('', '_cuentame'),
    indicator=True)

for c in [c for c in abastecimiento_cuentame_2025.columns if c.endswith('_cuentame')]:
    abastecimiento_cuentame_2025.drop(columns=[c], inplace=True)
abastecimiento_cuentame_2025.drop(columns=['_merge'], inplace=True)
abastecimiento_cuentame_2025.rename(columns=rename_dict, inplace=True)

abastecimiento_cuentame = pd.concat([abastecimiento_cuentame, abastecimiento_cuentame_2025])
print(f'Registros finales: {len(abastecimiento_cuentame)} (original: {len(abastecimiento_df)})')
len(abastecimiento_cuentame)

C:\Users\User\AppData\Local\Temp\ipykernel_19056\1828189015.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:
C:\Users\User\AppData\Local\Temp\ipykernel_19056\1828189015.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:
C:\Users\User\AppData\Local\Temp\ipykernel_19056\1828189015.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

Registros finales: 21013 (original: 21013)

21013

In [53]:
abastecimiento_cuentame.columns

Index(['Número de Zona', 'Regional UDS', 'Centro Zonal UDS', 'Municipio UDS',
       'Codigo Unidad Servicio UDS', 'Unidad Servicio UDS', 'Servicio 2026',
       'Cupos UDS ofertados 2026', 'Entidad Contratista\n2026',
       'NIT_EntidadContratista', 'Número de contrato ', 'Código UDS',
       'Departamento UDS', 'Barrio UDS', 'Nombre Servicio', 'Vigencia UDS',
       'Estado UDS', 'Direccion UDS', 'Servicio', 'RegionalUDS',
       'MunicipioUDS', 'CentroZonalUDS'],
      dtype='str')

In [54]:
import win32com.client as win32
import numpy as np

formato_path = base_path + formato

col_map = {
    'Número de Zona': 'Número de Zona',
    'Número de contrato ': 'Número de contrato ',
    'NIT_EntidadContratista': 'Identificación EC',
    'Entidad Contratista\n2026': 'Entidad Contratista\n2026',
    'Servicio 2026': 'Servicio 2026',
    'Regional UDS': 'Regional UDS',
    'Departamento UDS': 'Departamento UDS',
    'Municipio UDS': 'Municipio UDS',
    'Centro Zonal UDS': 'Centro Zonal UDS',
    'Codigo Unidad Servicio UDS': 'Codigo Unidad Servicio UDS',
    'Unidad Servicio UDS': 'Unidad Servicio UDS',
    'Barrio UDS': 'Barrio UDS',
    'Direccion UDS': 'Direccion UDS',
    'Estado UDS': 'Estado UDS',
    'Vigencia UDS': 'Vigencia UDS',
    'Cupos UDS ofertados 2026': 'Cupos UDS ofertados 2026',
}

col_const = {
    'Modalidad\n2026': 'INTEGRAL',
}

def _col_letter(n):
    letters = ''
    while n > 0:
        n -= 1
        letters = chr(65 + n % 26) + letters
        n //= 26
    return letters

# Mapear nombre de columna del formato a su letra de Excel
formato_header = pd.read_excel(formato_path, sheet_name='zonificacion', nrows=0).columns.tolist()
col_name_to_letter = {name: _col_letter(i+1) for i, name in enumerate(formato_header)}

# --- Escribir con xlwings ---
import xlwings as xw
import os

os.system('attrib -R "{}"'.format(formato_path))

app = xw.App(visible=False)
wb = app.books.open(formato_path)
ws = wb.sheets['zonificacion']

nrows = len(abastecimiento_cuentame)

for src_col, tgt_col in col_map.items():
    col_letter = col_name_to_letter[tgt_col]
    ws.range(f'{col_letter}2:{col_letter}{nrows+1}').value = None
    values = abastecimiento_cuentame[src_col].tolist()
    values = [[None if pd.isna(v) else v] for v in values]
    ws.range(f'{col_letter}2').value = values
    print(f'  Escrita columna {tgt_col} ({col_letter})')

for tgt_col, const_val in col_const.items():
    col_letter = col_name_to_letter[tgt_col]
    ws.range(f'{col_letter}2:{col_letter}{nrows+1}').value = None
    ws.range(f'{col_letter}2').options(transpose=True).value = [const_val] * nrows
    print(f'  Escrita columna constante {tgt_col} ({col_letter})')

wb.save()
wb.close()
app.quit()

print(f'Formato actualizado correctamente: {nrows} filas escritas en {formato_path}')

  Escrita columna Número de Zona (A)
  Escrita columna Número de contrato  (B)
  Escrita columna Identificación EC (C)
  Escrita columna Entidad Contratista
2026 (D)
  Escrita columna Servicio 2026 (F)
  Escrita columna Regional UDS (G)
  Escrita columna Departamento UDS (H)
  Escrita columna Municipio UDS (I)
  Escrita columna Centro Zonal UDS (K)
  Escrita columna Codigo Unidad Servicio UDS (M)
  Escrita columna Unidad Servicio UDS (N)
  Escrita columna Barrio UDS (O)
  Escrita columna Direccion UDS (P)
  Escrita columna Estado UDS (Q)
  Escrita columna Vigencia UDS (R)
  Escrita columna Cupos UDS ofertados 2026 (S)
  Escrita columna constante Modalidad
2026 (E)
Formato actualizado correctamente: 21013 filas escritas en D:/ICBF/cost-tracking/data/insumos 4 junio/zonificación_integrales_2026_ajustado.xlsx